[build]
  command = "npm run production"
  publish = "dist"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs]
    output_path = "reports/lighthouse.html"

    # optional, fails build when a category is below a threshold
    [plugins.inputs.thresholds]
      performance = 0.9
      accessibility = 1
      best-practices = 1
      seo = 1
      pwa = 1

    [[plugins.inputs.audits]]
      url = "https://bram.is"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; font-src 'self' fonts.gstatic.com; style-src 'unsafe-inline' fonts.googleapis.com; script-src 'unsafe-inline' plausible.io; worker-src 'self'; connect-src 'self' plausible.io"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "interest-cohort=()"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=604800"


[[redirects]]
  from = "http://bramsmulders.com/*"
  to = "https://bram.is/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://bramsmulders.com/*"
  to = "https://bram.is/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.bramsmulders.com/*"
  to = "https://bram.is/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.bramsmulders.com/*"
  to = "https://bram.is/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/blog"
  to = "/writing"
  status = 301
  force = true

[[redirects]]
  from = "/about"
  to = "/awesome"
  status = 301
  force = true

[[redirects]]
  from = "/posts"
  to = "/writing"
  status = 301
  force = true

[[redirects]]
  from = "/married-to-saskia"
  to = "https://www.icloud.com/sharedalbum/nl-nl/#B0j5n8hH4GvdZr2"
  force = true

[[redirects]]
  from = "/blog/how-i-improved-my-workflow-with-smacss-sass"
  to = "/writing/how-i-improved-my-workflow-with-smacss-sass"
  status = 301
  force = true

[[redirects]]
  from = "/how-i-improved-my-workflow-with-smacss-sass.html"
  to = "/writing/how-i-improved-my-workflow-with-smacss-sass"
  status = 301
  force = true

[[redirects]]
  from = "/posts/how-i-improved-my-workflow-with-smacss-sass"
  to = "/writing/how-i-improved-my-workflow-with-smacss-sass"
  status = 301
  force = true


[[redirects]]
  from = "/blog/finger-friendly-all-the-things"
  to = "/writing/finger-friendly-all-the-things"
  status = 301
  force = true

[[redirects]]
  from = "/posts/finger-friendly-all-the-things"
  to = "/writing/finger-friendly-all-the-things"
  status = 301
  force = true

[[redirects]]
  from = "/finger-friendly-all-the-things.html"
  to = "/writing/finger-friendly-all-the-things"
  status = 301
  force = true


[[redirects]]
  from = "/blog/i-am-fine-just-an-introvert"
  to = "/writing/i-am-fine-just-an-introvert"
  status = 301
  force = true

[[redirects]]
  from = "/posts/i-am-fine-just-an-introvert"
  to = "/writing/i-am-fine-just-an-introvert"
  status = 301
  force = true

[[redirects]]
  from = "/i-am-fine-just-an-introvert.html"
  to = "/writing/i-am-fine-just-an-introvert"
  status = 301
  force = true


[[redirects]]
  from = "/blog/atomic-design-at-fronteers-meetup"
  to = "/writing/atomic-design-at-fronteers-meetup"
  status = 301
  force = true

[[redirects]]
  from = "/posts/atomic-design-at-fronteers-meetup"
  to = "/writing/atomic-design-at-fronteers-meetup"
  status = 301
  force = true

[[redirects]]
  from = "/blog/structured-frontend-components"
  to = "/writing/structured-frontend-components"
  status = 301
  force = true


