[build]
  command = "npm run production"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self';"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = 1
    X-Content-Type-Options = "nosniff"


[[redirects]]
  from = "http://bramsmulders.com/*"
  to = "https://bram.is/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://bramsmulders.com/*"
  to = "https://bram.is/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.bramsmulders.com/*"
  to = "https://bram.is/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.bramsmulders.com/*"
  to = "https://bram.is/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/blog"
  to = "/writing"
  status = 301
  force = true

[[redirects]]
  from = "/about"
  to = "/awesome"
  status = 301
  force = true

[[redirects]]
  from = "/posts"
  to = "/writing"
  status = 301
  force = true

[[redirects]]
  from = "/blog/how-i-improved-my-workflow-with-smacss-sass"
  to = "/writing/how-i-improved-my-workflow-with-smacss-sass"
  status = 301
  force = true

[[redirects]]
  from = "/how-i-improved-my-workflow-with-smacss-sass.html"
  to = "/writing/how-i-improved-my-workflow-with-smacss-sass"
  status = 301
  force = true

[[redirects]]
  from = "/posts/how-i-improved-my-workflow-with-smacss-sass"
  to = "/writing/how-i-improved-my-workflow-with-smacss-sass"
  status = 301
  force = true


[[redirects]]
  from = "/blog/finger-friendly-all-the-things"
  to = "/writing/finger-friendly-all-the-things"
  status = 301
  force = true

[[redirects]]
  from = "/posts/finger-friendly-all-the-things"
  to = "/writing/finger-friendly-all-the-things"
  status = 301
  force = true

[[redirects]]
  from = "/finger-friendly-all-the-things.html"
  to = "/writing/finger-friendly-all-the-things"
  status = 301
  force = true


[[redirects]]
  from = "/blog/i-am-fine-just-an-introvert"
  to = "/writing/i-am-fine-just-an-introvert"
  status = 301
  force = true

[[redirects]]
  from = "/posts/i-am-fine-just-an-introvert"
  to = "/writing/i-am-fine-just-an-introvert"
  status = 301
  force = true

[[redirects]]
  from = "/i-am-fine-just-an-introvert.html"
  to = "/writing/i-am-fine-just-an-introvert"
  status = 301
  force = true


[[redirects]]
  from = "/blog/atomic-design-at-fronteers-meetup"
  to = "/writing/atomic-design-at-fronteers-meetup"
  status = 301
  force = true

[[redirects]]
  from = "/posts/atomic-design-at-fronteers-meetup"
  to = "/writing/atomic-design-at-fronteers-meetup"
  status = 301
  force = true

[[redirects]]
  from = "/blog/structured-frontend-components"
  to = "/writing/structured-frontend-components"
  status = 301
  force = true


